# Generated by Django 5.0.4 on 2024-04-14 23:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yalloweme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 14, 23, 29, 48, 548623, tzinfo=datetime.timezone.utc)),
        ),
    ]
